# Auto-generated by tools/scripts/get_jlink.py — do not edit manually.
# Re-run the script to change the active J-Link.
# Active source: local  (JLink_V840)
# To switch:  python tools/scripts/get_jlink.py --source system
override JLINK := $(CURDIR)/tools/jlink/JLink_Windows_V840_x86_64/JLink_V840/JLink.exe
