# Auto-generated by tools/scripts/get_openocd.py — do not edit manually.
# Re-run the script to change the active OpenOCD.
# Active source: local  (xpack-openocd-0.12.0-7)
# To switch:  python tools/scripts/get_openocd.py --source system
override OPENOCD := $(CURDIR)/tools/openocd/xpack-openocd-0.12.0-7/bin/openocd.exe
