# Auto-generated by tools/scripts/get_toolchain.py — do not edit manually.
# Re-run the script to change the active toolchain.
# Active source: system  (arm-none-eabi-* resolved from PATH)
# To switch:  python tools/scripts/get_toolchain.py --source local
